services:
  spark-master:
    build:
      context: .
      dockerfile: spark/Dockerfile
    entrypoint: [ './entrypoint.sh', 'master' ]
    networks:
      - local-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - spark-logs:/opt/spark/spark-events
      - ./data:/app/data
      - ./notebooks:/app/notebooks
    env_file:
      - spark/env.spark
    ports:
      - '8080:8080'
      - '7077:7077'
      - '8888:8888'

  spark-worker:
    build:
      context: .
      dockerfile: spark/Dockerfile
    entrypoint: [ './entrypoint.sh', 'worker' ]
    networks:
      - local-network
    depends_on:
      spark-master:
        condition: service_healthy
    env_file:
      - spark/env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events

networks:
  local-network:
    driver: bridge

volumes:
  spark-logs:
